name: Build app and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # main分支，你也可以改成其他分支
      - main
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@main
      # 安装Node
      - name: use Node.js 16.13.1
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      # 安装依赖
      - name: npm install
        run: |
          npm install
          npm i esbuild-linux-64
      # 打包
      - name: npm build
        run: npm run docs:build
      # 部署到阿里云
      - name: Deploy to Aliyun
        uses: garygrossgarten/github-action-scp@release
        env:
          # 私钥
          privateKey: ${{ secrets.ACCESS_KEY_SECRET }}
          # 源目录，编译后生成的文件目录
          local: "./docs/.vitepress/dist"
          # 服务器ip：换成你的服务器IP
          host: "120.25.159.52"
          port: "22"
          # 用户
          username: "root"
          # 目标地址 你在服务器上部署代码的地方
          remote: "/home/html/note"
